cacheFolder: "./.yarn/cache"

nodeLinker: pnp

pnpMode: "loose"

yarnPath: .yarn/releases/yarn-3.2.3.cjs

packageExtensions:
  "@prisma/client@*":
    dependencies:
      ".prisma": 'link:See "resolution" field of package.json'
