#####
# Documentation
# Redwood: https://render.com/docs/deploy-redwood
# YAML (all config values): https://render.com/docs/yaml-spec
#####

services:
- name: oauth2-server-redwood-web
  type: web
  env: static
  buildCommand: yarn install && yarn rw deploy render web
  staticPublishPath: ./web/dist
  envVars:
  - key: NODE_VERSION
    value: 16
  - key: SKIP_INSTALL_DEPS
    value: true
  routes:
  - type: rewrite
    source: /.redwood/functions/*
    destination: https://oauth2-server-redwood-api.onrender.com/*
  - type: rewrite
    source: /*
    destination: /index.html

- name: oauth2-server-redwood-api
  type: web
  plan: free
  env: node
  region: oregon
  buildCommand: yarn && yarn build-packages && yarn rw build api
  startCommand: yarn rw deploy render api
  envVars:
  - key: NODE_VERSION
    value: 16
  - key: DATABASE_URL
    fromDatabase:
      name: oauth2-server-redwood-db
      property: connectionString

databases:
  - name: oauth2-server-redwood-db
    region: oregon

